name: 'Lockfile Guard'
description: 'Lints for improper JS package manager usage (npm, pnpm, yarn, bun) to enforce supply chain security'
author: 'Your Name'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  commit:
    description: 'Specific commit SHA to use (defaults to latest on main branch)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Download lockfile-guard binary
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # Repository where lockfile-guard is published
        LOCKFILE_GUARD_REPO="johnsaigle/lockfile-guard"
        
        # Determine which commit to use
        COMMIT="${{ inputs.commit }}"
        if [ -z "$COMMIT" ]; then
          echo "No commit specified, fetching latest from main branch..."
          COMMIT=$(curl -s "https://api.github.com/repos/${LOCKFILE_GUARD_REPO}/commits/main" | grep '"sha"' | head -1 | sed -E 's/.*"([^"]+)".*/\1/')
        fi
        
        echo "Using lockfile-guard from commit: ${COMMIT}"
        
        # Try to download artifact from GitHub Actions
        echo "Downloading binary artifact from ${LOCKFILE_GUARD_REPO}..."
        
        # Use gh CLI to download artifact if available
        if command -v gh &> /dev/null; then
          # Try to download the specific commit artifact first
          if gh run download --repo "${LOCKFILE_GUARD_REPO}" -n "lockfile-guard-${COMMIT}" 2>/dev/null; then
            mv lockfile-guard-linux-x64 lockfile-guard
            chmod +x lockfile-guard
            echo "Successfully downloaded binary for commit ${COMMIT}"
          # Fall back to latest
          elif gh run download --repo "${LOCKFILE_GUARD_REPO}" -n "lockfile-guard-latest" 2>/dev/null; then
            mv lockfile-guard-linux-x64 lockfile-guard
            chmod +x lockfile-guard
            echo "Successfully downloaded latest binary"
          else
            echo "Error: Could not download binary artifact."
            echo "Please ensure the lockfile-guard repository has built binaries available."
            exit 1
          fi
        else
          echo "Error: gh CLI not available. Cannot download artifacts."
          exit 1
        fi

    - name: Run lockfile-guard
      shell: bash
      run: ./lockfile-guard
